project:
  type: website
  output-dir: docs

execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "Psych 434"
  navbar:
    search: false
    right:
    - text: "Content"
      menu:
        - text: "Preliminaries"
          href: content/index.qmd
        - text: "1: How to ask a why question"
          href: content/01-content.qmd

format:
  html:
    theme: lumen
    toc: true
    css: styles.css
    html-math-method: katex

license: MIT # CC BY-NC-SA if any data are used

