---
title: "Psych 434: Conducting Research Across Cultures"
---


Welcome to the Psych 434 lecture website.

**You can access the course lectures by navigating to the "Contents" section and selecting the appropriate tab**


## Class times and locations

**Lectures** Day/Time: Tuesday, 1:10-3:00pm

**Lecture Location** All classes are in Easterfield Building EA407


## Names and contact details

**Course Coordinator** Prof Joseph Bulbulia <joseph.bulbulia@vuw.ac.nz>

**Room** EA324 

**Lectures** Dr.Inkuk Kim  <inkuk.kim@vuw.ac.nz>

**Lectures** Torven Schalk <torven.schalk@vuw.ac.nz>



## Course Description 

The official description:

*This course will focus on theoretical and practical challenges for conducting research involving individuals from more than one cultural background or ethnicity. Topics are likely to include defining and measuring culture; developing culture-sensitive studies, choice of language and translation; communication styles and bias; questionnaire and interview design; qualitative and quantitative data analysis for cultural and cross-cultural research; minorities, power and ethics in cross-cultural research; and ethno-methodologies and indigenous research methodologies. Appropriate background for this course: PSYC 338. *


## Course learning objectives 

This course is an introduction to conducting research in cross-cultural psychology. Our goal is to provide you with the tools and concepts you will need to conduct cross-cultural research.

The primary focus of this course is to develop your skills for collecting, analysing, and interpreting cultural data. By the end of the course, you will be prepared to contribute to cross-cultural research projects. While some of you may not pursue cross-cultural research in the future, the training you will receive will be invaluable for a wide range of tasks you may face as you navigate the complexities of cultural diversity in your personal and professional lives.

Foremost among these skills is ethical reasoning. Beginning in week 1, we will explore questions that are typically reserved for philosophy courses but are central to the conduct of psychology: why do we need to think about right and wrong in science? What if different people have different ideas about what is right and wrong in science? Is there hope for ethical progress? Can science play a role in ethical progress?  We will provide you with a set of strategies for addressing these questions.

Again, the primary focus of this course is impart analytical skills that are essential for conducting cross-cultural research.  Beginning in week 2, we will teach you the basics of programming in the statistical language R. The past several decades have brought extraordinary new tools to psychological scientists, many of which require literacy in computer programming. While some of you may find the thought of programming thrilling, others may find it terrifying or boring! We promise that programming can be fun. This course is designed to help you find that joy.

At the heart of cultural research are problems of interpretation. Beginning in week 3 the course will turn its focus to developing skills for constructing and validating measures in cross-cultural research. Again these skills will be invaluable for a wide range of tasks you may face in psychological science and will help you to address problems that will arise in other areas of your research and work. Measurement will occupy our attention through week 6.

Causal inference is a holy grail of all psychological research. Beginning in week 7 and for the following four weeks, the course will impart skills that you require to disentangle causation from correlation. Again our focus will be on the special problems that arise for cultural datasets. Notably, in psychological science, causal inference remains underdeveloped, and the material in this part of the course will position you to make potentially important contributions, whether or not your interests lie in cross-cultural psychology.

In the final two seminars, we will return to considerations of ethics and ownership in cross-cultural research, and look ahead to future directions. The practice sessions in these seminars will be devoted to helping students with their projects.





