---
title: "How to ask a Why Question"
subtitle: "And why to ask a why question"
format:
  revealjs: 
    slide-number: true
    smaller: false
    scrollable: true
    incremental: true
    chalkboard: true 
    buttons: false
    preview-links: auto
    theme: dark
    css: styles.css
    embed-resources: false
    code-fold: false
    code-overflow: scroll
    code-line-numbers: true
    auto-stretch: true
    html-math-method: katex

---



## Why questions

Why why? 



## Test


At the core: 

\[ Y|A=1  \neq Y_{0} \]

::: {.r-fit-text}

:::


## Dags

```{r}
library(ggdag)
library(dplyr)

coords <- read.table(header = TRUE, text = "
  x y name
  0 1 U
  1 .1 L0
  2 0 A0
  3 0.1 Y0
  4 0 A1
  5 0.2 Y2
")

d <- dagify(
  A0 ~ L0,
  A1 ~ A0,
  L0 ~ U,
  Y0 ~ A0,
  Y2 ~ A1 + L0,
  Y2 ~ U + Y0,
  coords = coords)

ggdag(d) +
   theme_dag()

```


## Code 
```{.r}
library(ggdag)
library(dplyr)


coords <- read.table(header = TRUE, text = "
  x y name
  0 1 U
  1 0 L0
  2 0 A0
  3 0 Y0
  4 0 A1
  5 0 Y2
")

d <- dagify(
  A1 ~ L0 + A0,
  L0 ~ U,
  Y0 ~ U,
  Y2 ~ A1,
  Y2 ~ U + Y0,
  coords = coords)

ggdag(d) +
   theme_dag()
```


##  DAG 
```{r}
library(dagitty)
library(ggdag)

# coordinates for graph
coords <- read.table(header = TRUE, text = "
  x y name
  0 -1 U
  0 1 L
  2 0 A0
  3 0 Y0
  4 0 A1
  6 0 Y2
")

# make into daggity object
d <- dagify(
  L ~ U,
  A0 ~  L + U,
  Y0 ~  L + U,
  A1 ~  L + U ,
  Y2 ~  L + U,
  exposure = "A1",
  outcome = "Y2",
  latent = "U",
  coords = coords)

# plot
ggdag(d,  text = TRUE, node = FALSE, 
      text_size = 9,
      text_col = "black") +
   theme_dag()

```

## Check confounding

```{r}
ggdag_adjustment_set(d) + theme_dag_blank()
```

## Visualise confounding


```{r}
ggdag_dseparated(d,
  controlling_for = c("L", "A0", "Y0"),
  text = TRUE, collider_lines = FALSE
) + theme_dag()
```



## test dag

```{.r}
install.packages(c("coda","mvtnorm","devtools","loo","dagitty","shape"))
devtools::install_github("rmcelreath/rethinking")
library(rethinking)
drawdag(d, arrow = "gray",  Z=list("U"))
```


###

https://gist.github.com/andrewheiss/4ece621813a27dfdcaef7f1c2d773237
