---
title: "Template: Causal Estimatatio"
date: "2023-MAY-30"
author:
    name: Joseph Bulbulia
    orcid: 0000-0002-5861-2056
    affiliation: Victoria University of Wellington, New Zealand
    email: joseph.bulbulia@vuw.ac.nz
    corresponding: yes
bibliography: references.bib
---



## Intoduction

Answer the following: 

- Stating the Question: Is my question clearly stated? If not, state it.
- Relevance of the Question: Have I explained its importance? If not, explain.
-  Subgroup Analysis: Does my question involve a subgroup (e.g., cultural group)? If not, develop a subgroup analysis question.
-  Causality of the Question: Is my question causal?  Briefly explain what this means with reference to the potential outcomes framework. 
-  State how you will use time-series data to address causality.
-  Define your exposure. 
-  Define your outcome(s)
-  Explain how the the exposure and outcome is relevant to your question.


Methods
-  Explain the sample. 
-  In your own words describe the assumptions required for causal inference: 
  -  Positivity: Can we intervene on the exposure at all levels of the covariates? 
  -  Consistency: Can I interpret what it means to intervene on the exposure? 
  -  Exchangeability: Are different versions of the exposure conditionally exchangeable given measured baseline confounders?
  This requires stating baseline Confounders and explaining how they may be related to both the exposure and outcome. 
  As part of this, you must explain why the baseline measure of your exposure and outcome are included as potential confounders. 
- Note: Unmeasured Confounders: Does previous science suggest the presence of unmeasured confounders? (e.g. childhood exposures that are not measured).
- Draw a causal diagram: Have I drawn a causal diagram (DAG) to highlight both measured and unmeasured sources of confounding? 
- Measurement Error: Have I described potential biases from measurement errors? 

